#!/usr/bin/python3
# encoding: utf-8
"""
https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will
be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in
the Fibonacci sequence whose values do not exceed four million, find
the sum of the even-valued terms.

Answer: 4613732
"""
from __future__ import print_function


def fib(max, a=0, b=1):
    x = 0

    while x < max:
        x = a + b
        a = b
        b = x

        yield x


if __name__ == '__main__':
    print(sum(x for x in fib(4000000) if not x % 2))
