#!/usr/bin/python3
# encoding: utf-8
"""
https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will
be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in
the Fibonacci sequence whose values do not exceed four million, find
the sum of the even-valued terms.

Answer: 4613732
"""
from __future__ import print_function
from utils import timer, fib, take_upto


ANSWER = 4613732


def test_answer():
    if ANSWER is None:
        assert 0, 'Not Completed'
    else:
        assert ANSWER == main()


@timer
def main():
    return sum(x for x in take_upto(4000000, fib()) if not x % 2)


if __name__ == '__main__':
    print(main())
