#!/usr/bin/python3
# encoding: utf-8
"""
https://projecteuler.net/problem=44

Pentagonal numbers are generated by the formula.
    P_n = n (3 n −1)/2.
The first ten pentagonal numbers are:
    1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8.
However, their difference, 70 − 22 = 48, is not pentagonal.
Find the pair of pentagonal numbers, P_j and P_k ,
for which their sum and difference are pentagonal and
D = |P_k − P_j | is minimised; what is
the value of D?

Answer: 5482660
"""
from __future__ import print_function
from utils import timer, is_pentagonal_number
import itertools
import sys

def pents():
    count = 1
    while True:
        pent = ((3 * (count ** 2)) - count) / 2
        count += 1
        yield pent


@timer
def main():
    diff = int(1e9)
    for k in pents():
        for j in pents():
            d = abs(k - j)
            s = k + j
            if is_pentagonal_number(d) and is_pentagonal_number(s):
                return('k: {0}, j: {1}, diff: {2}, sum: {3}'.format(k, j, d, s))
            else:
                if d > diff:
                    break


if __name__ == '__main__':
    print(main())
