#!/usr/bin/python3
# encoding: utf-8
"""
https://projecteuler.net/problem=45

Triangle, pentagonal, and hexagonal numbers are generated by the
following formulae:
    Triangle T_n = n(n+1)/2      1, 3, 6, 10, 15, ...
    Pentagonal P_n = n(3n−1)/2   1, 5, 12, 22, 35, ...
    Hexagonal H_n = n(2n−1)      1, 6, 15, 28, 45, ...
It can be verified that T_285 = P_165 = H_143 = 40755.
Find the next triangle number that is also
pentagonal and hexagonal.

Answer: 1533776805
"""
from __future__ import print_function
from utils import timer, is_pentagonal_number


def hexagonal_gen(start=1):
    count = start
    while True:
        yield count * (2*count - 1)
        count += 1


@timer
def main():
    for h in hexagonal_gen(144):
        if is_pentagonal_number(h):
            return h


if __name__ == '__main__':
    print(main())
