package main

// https://projecteuler.net/problem=2
//
// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms will
// be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in
// the Fibonacci sequence whose values do not exceed four million, find
// the sum of the even-valued terms.

// Answer: 4613732

import (
	"fmt"
	u "utils"
)

func main() {
	sum := 0

	for v := range u.TakeUpto(u.Mill*4, u.FibonnaciGenerator()) {
		if u.ModInt(v, 2) == 0 {
			sum += v
		}
	}

	fmt.Println(sum)
}
